# Site settings
title: 成乐乐的博客
email: ch_lele2009@126.com
description: > # this means to ignore newlines until "baseurl:"
  成乐乐的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://chenglele.org # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: chenglele

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
twitter: masonchenglele
weibo: chenglele0830
github: chenglele
instagram: chenglele0830
linkedin: chenglele0830

# avatar and Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# disqus config
disqus:
  shortname: chenglele-zh

# google analytics config
ga:
  id: UA-54767140-1
  url: chenglele.org

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

theme: jekyll-theme-cayman